/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package interfacegrafica3.view;

import interfacegrafica3.model.Pessoa;
import interfacegrafica3.repository.Conexao;
import interfacegrafica3.repository.ConexaoMySQL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Professor
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    JanelaCadastro janelaCadastro;
    JanelaCadastroUF janelaCadastroUF;
    public List<Pessoa> lstPessoa;
    public int ultimoId;
    private Conexao conexao;
    public ConexaoMySQL conexaoMySQL;

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        lstPessoa = new ArrayList<>();
        ultimoId = 0;
        conexao = new Conexao(
                "localhost",
                "root",
                "",
                3306,
                "cadastro"
        );
        conexaoMySQL = new ConexaoMySQL(conexao);
        conexaoMySQL.conectar();
        //Pessoa p = new Pessoa("Pessoa1", "email","end","tel",1);
        //conexaoMySQL.insert(p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jB_fornecedor = new javax.swing.JButton();
        jB_cadastro = new javax.swing.JButton();
        jB_cadastroUf = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        openMenuItem1 = new javax.swing.JMenuItem();
        openMenuItem2 = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jB_fornecedor.setText("FORNECEDOR");
        jB_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_fornecedorActionPerformed(evt);
            }
        });
        desktopPane.add(jB_fornecedor);
        jB_fornecedor.setBounds(140, 280, 160, 50);

        jB_cadastro.setText("CADASTRO");
        jB_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cadastroActionPerformed(evt);
            }
        });
        desktopPane.add(jB_cadastro);
        jB_cadastro.setBounds(140, 140, 160, 50);

        jB_cadastroUf.setText("CADASTRO UF");
        jB_cadastroUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cadastroUfActionPerformed(evt);
            }
        });
        desktopPane.add(jB_cadastroUf);
        jB_cadastroUf.setBounds(140, 210, 160, 50);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("MENU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel1)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        desktopPane.add(jPanel1);
        jPanel1.setBounds(0, 0, 450, 100);

        fileMenu.setMnemonic('a');
        fileMenu.setText("Arquivo");

        openMenuItem.setMnemonic('c');
        openMenuItem.setText("Cadastro");
        openMenuItem.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                openMenuItemCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        openMenuItem1.setMnemonic('u');
        openMenuItem1.setText("Cadastro de UF");
        openMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem1);

        openMenuItem2.setMnemonic('u');
        openMenuItem2.setText("Cadastro de Fornecedor");
        openMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItem2ActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem2);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Sair");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('j');
        helpMenu.setText("Ajuda");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed

        try {
            janelaCadastro = JanelaCadastro.getInstancia(this);
            if (!desktopPane.isAncestorOf(janelaCadastro)) {
                desktopPane.add("JanelaCadastro", janelaCadastro);
                janelaCadastro.setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);
            }

            janelaCadastro.setSelected(true);
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(null,
                    "Erro ao abrir a tela de cadastro de clientes: ",
                    "Cadastro de clientes",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        //exibir a qte de dados da lista:
        JOptionPane.showMessageDialog(
                this,
                "Qte de pessoas: " + lstPessoa.size(),
                "Cadastro de clientes",
                JOptionPane.INFORMATION_MESSAGE
        );
        //imprimir todos os registros da minha lista:
        for (int i = 0; i < lstPessoa.size(); i++) {
            Pessoa p = lstPessoa.get(i);
            JOptionPane.showMessageDialog(
                    this,
                    p.toString(),
                    "Cadastro de pessoa",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void openMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItem1ActionPerformed
        //menu cadastro uf
        try {
            janelaCadastroUF = JanelaCadastroUF.getInstancia(this);
            if (!desktopPane.isAncestorOf(janelaCadastroUF)) {
                desktopPane.add("JanelaCadastroUF", janelaCadastroUF);
                janelaCadastroUF.setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);
            }

            janelaCadastroUF.setSelected(true);
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(null,
                    "Erro ao abrir a tela de cadastro de UF: ",
                    "Cadastro de UF",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_openMenuItem1ActionPerformed

    private void openMenuItemCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_openMenuItemCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_openMenuItemCaretPositionChanged

    private void openMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItem2ActionPerformed

        try {
            // Obtendo a instância da JanelaCadastroFornecedor
            JanelaCadastroFornecedor janelaCadastroFornecedor = JanelaCadastroFornecedor.getInstancia(this);

            // Verifica se a janela já está adicionada ao desktopPane
            if (!desktopPane.isAncestorOf(janelaCadastroFornecedor)) {
                desktopPane.add(janelaCadastroFornecedor);
            }

            // Exibe a janela e garante que ela está ativa
            janelaCadastroFornecedor.setVisible(true);
            janelaCadastroFornecedor.setSelected(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    "Erro ao abrir a tela de cadastro de fornecedor: " + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_openMenuItem2ActionPerformed

    private void jB_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cadastroActionPerformed
        try {
            // Obtendo a instância da JanelaCadastro
            JanelaCadastro janelaCadastro = JanelaCadastro.getInstancia(this);

            // Verifica se a janela já está adicionada ao desktopPane
            if (!desktopPane.isAncestorOf(janelaCadastro)) {
                desktopPane.add(janelaCadastro);
            }

            // Exibe a janela e a traz para frente
            janelaCadastro.setVisible(true);
            janelaCadastro.setSelected(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    "Erro ao abrir a tela de cadastro: " + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jB_cadastroActionPerformed

    private void jB_cadastroUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cadastroUfActionPerformed
        try {
            // Obtendo a instância da JanelaCadastroUF
            JanelaCadastroUF janelaCadastroUF = JanelaCadastroUF.getInstancia(this);

            // Verifica se a janela já está adicionada ao desktopPane
            if (!desktopPane.isAncestorOf(janelaCadastroUF)) {
                desktopPane.add(janelaCadastroUF);
            }

            // Exibe a janela e a traz para frente
            janelaCadastroUF.setVisible(true);
            janelaCadastroUF.setSelected(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    "Erro ao abrir a tela de cadastro de UF: " + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jB_cadastroUfActionPerformed

    private void jB_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_fornecedorActionPerformed
        try {
            // Obtendo a instância da JanelaCadastroFornecedor
            JanelaCadastroFornecedor janelaCadastroFornecedor = JanelaCadastroFornecedor.getInstancia(this);

            // Adiciona ao desktopPane se ainda não estiver adicionada
            if (janelaCadastroFornecedor.getParent() == null) {
                desktopPane.add(janelaCadastroFornecedor);
            }

            // Exibe e traz para frente
            janelaCadastroFornecedor.setVisible(true);
            janelaCadastroFornecedor.setSelected(true);
            janelaCadastroFornecedor.setIcon(false); // Caso esteja minimizada, restaurar

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao abrir a tela de cadastro de fornecedor: " + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jB_fornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jB_cadastro;
    private javax.swing.JButton jB_cadastroUf;
    private javax.swing.JButton jB_fornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem openMenuItem1;
    private javax.swing.JMenuItem openMenuItem2;
    // End of variables declaration//GEN-END:variables

}
